# DNSmasq 配置
# 监听 5353 端口
port=5353
# 不读取 /etc/hosts
no-hosts
# 不分配 DHCP
no-dhcp-interface=
# 上游 DNS
server=8.8.8.8
server=1.1.1.1
# 本地域名解析
address=/complex.test/127.0.0.1
address=/app.test/127.0.0.1
# 日志
log-queries
